name: Pull Request Check
# onはトリガー、今回はpull request
on: [ pull_request ]
# envは環境変数
env:
  JAVA_VERSION: 17
  GRADLE_VERSION: 8.2
# プルリクエストに書き込み権限を付与
permissions:
  pull-requests: write

jobs:
  android-lint:
    runs-on: ubuntu-latest
    steps:
      # setup
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
          # gradlewファイルに実行権限を付与
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # android lintを実行
      - name: Android Lint
        id: android-lint
        run: ./gradlew lint

      # SARIFファイルの場所を確認(デバック用)
      - name: Find SARIF files
        run: find . -name "*lint*.sarif"

      # report
      - name: Comment PR by reviewdog
        if: always()
        run: |
          find . -name "*lint*.sarif" \
            -type f \
            -exec sh -c "cat {} | reviewdog -f=sarif -reporter=github-pr-review" \;
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ktlint:
    runs-on: ubuntu-latest
    steps:
      # setup
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          # 不正なコードはFailureで検出
          fail_on_error: true